### ISSUE TITLE
Add extensible !duck commands

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#10]
Add command-esque things to the bot. Would allow us to add loads of commands as we want.

`!duck help` to list commands and short descriptions.

`!duck repo` to link to the repo.

**Comment by twentylemon** [comment]
#7 could also be `!duck stock [day|week|month|year]` to avoid noise in the channel

**Comment by Chippers255** [comment]
commands don't have to be !duck something. Due to the command structure of the discord python library we can initialize any command with a symbol instead of a keyword (eg: !stock [day|week|month|year]).

**Comment by twentylemon** [comment]
If that's the case, then this can be yeeted.
