### ISSUE TITLE
add weekly gluten picture/recipe, or !recipe command

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#13]

**Comment by Chippers255** [comment]
Looks relatively easy to search and filter recipes on allrecipies based on ingredients. I am going to take a first crack at this.

**Comment by twentylemon** [comment]
@Chippers255 update the [wiki](https://github.com/Chippers255/duckbot/wiki). Close this after that's done.

**Comment by Chippers255** [comment]
Done
