### ISSUE TITLE
Post to #duckbutt when an issue or pull request is opened

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#19]
Maybe.

**Comment by Chippers255** [comment]
do it

**Comment by twentylemon** [comment]
https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Comment by Chippers255** [comment]
I have added the webhook to this project

**Comment by Chippers255** [comment]
![image](https://user-images.githubusercontent.com/3149083/108526442-26b9a800-729f-11eb-82f9-b2320b65a7a7.png)
![image](https://user-images.githubusercontent.com/3149083/108526494-3507c400-729f-11eb-8a71-afedb5b79858.png)
