### ISSUE TITLE
`!logs` to attach logs to a discord message

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#210]
At some point #208 will get merged in and we'll have logs. The duckbot instance is unreachable for most of us, so it'd be nice to have a way for anyone to fetch the logs when stuff goes wrong. And then, hopefully `!logs` never fails.

[Context#send](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Context.send) accepts up to 10 files to send. We could either zip all the logs up, or just send all of the raw files.

**Comment by jameshughes89** [comment]
You thinking something like `!logs X -> tail -n X duck.log` ?

**Comment by twentylemon** [comment]
No, we won't know how many lines or files of logs we'll need to debug until we get them. A no arg command which fetches all logs I think would be best. Plus, we want it to always work, so probably best to keep it as simple as possible.
