### ISSUE TITLE
ensure execptions are logged

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#212]
Logs were added in #208, but apparently discord-py only dumps exceptions to stderr by default. See [Bot#on_command_error](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Bot.on_command_error) and [Client#on_error](https://discordpy.readthedocs.io/en/stable/api.html#discord.Client.on_error). The docs mention to override it, which we can do to cram traces into the logs. I think also dumping to stderr still makes sense, but we definitely want exceptions in logs.

**Comment by jameshughes89** [comment]
Currently we log command errors, but still need to figure out `on_message` & `task`.

**Comment by jameshughes89** [comment]
The message and task exceptions are still a TODO.
