### ISSUE TITLE
The *Redacted* Issue

### ISSUE THREAD

**Issue by Graevw** [duck-dynasty/duckbot#24]
auto respond to 25% of what *Redacted* says with "Wow that was insightful" or "This was both educational and intelligent."

**Comment by twentylemon** [comment]
Probably don't want to respond to literally everything he says with that. Maybe only in #memes, or a small chance in any channel.

**Comment by Chippers255** [comment]
We may be able to use some NLP libraries to determine the tone of what he says, if it sounds like he is making a statement it should respond with that kind of message.

**Comment by twentylemon** [comment]
Fixed by #61
