### ISSUE TITLE
investigate/add LGTM to repo

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#286]
[LGTM](https://lgtm.com/) is a thing, it gives out code quality badges, and performs a bunch of the stuff sonarcloud seems to like security checks. LGTM is github's product, so maybe worth using that in addition to, or instead of sonarcloud.

**Comment by Chippers255** [comment]
I agree, we should find an alternative to sonar cloud. It is rather clunky. I will test connecting LGTM to our project for a couple PRs to see how it compares.

**Comment by Chippers255** [comment]
It seems that LGTM is a little slow to run it's analysis.
- Our CI for a pull request took 2m55s
- Sonar Cloud scan took 37s
- LGTM scan took 29m 52s

**Comment by twentylemon** [comment]
Quite slow. I did see there's a `lgtm.yml` file we can add to the repo (haven't looked into it, just saw it in passing). I wonder if we can configure some stuff to speed it up.

In general though, 30min for a PR check probably isn't a deal breaker. Most PRs will have downtime before someone actually gets to it to review. The times it hurts is when there's a "high" priority fix going out (where we can ignore the results I guess), and  when someone clicks update on the PR while they start a review. That one is a little annoying...

**Comment by twentylemon** [comment]
Another option is to only have LGTM run on pushes into main so we can have the code quality badge. Which is just more pleasant than sonarcloud's badge.
