### ISSUE TITLE
Detect build errors during approval steps

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#31]
The current automatic approvals don't check for things like import errors or using undeclared variables, etc. Tests don't necessarily capture it since the imports are different between src and tests; and tests may no cover all the code.

**Comment by lapp14** [comment]
Im not super familiar with GitHub CI specifically, but we could make a CI job to run the tests and Flake8 or some other linter, and this way we can enforce green pipelines before merging a PR

**Comment by twentylemon** [comment]
> Im not super familiar with GitHub CI specifically, but we could make a CI job to run the tests and Flake8 or some other linter, and this way we can enforce green pipelines before merging a PR

That's [already done for pull requests](https://github.com/Chippers255/duckbot/blob/main/.github/workflows/python-package.yml#L13-L34). The problem is that tests can still pass when `py main.py` fails to interpret, due to something like import errors. Or, more simply, the broken files may just be untested. The point here isn't to gate test or code quality, rather just to ensure that the bot can still run -- correct or not -- if the pull request is merged in.

**Comment by twentylemon** [comment]
https://docs.github.com/en/actions/guides/building-and-testing-python
https://docs.python.org/3/library/py_compile.html

**Comment by twentylemon** [comment]
There's also a repo option we can set to avoid #62 again. We'd still need to ensure uncovered code is not breaking, such as `main.py`.
Settings -> Branches -> Branch protect rule (main) -> Require status checks to pass before merging (check option) -> Require branches to be up to date before merging (check option)

https://docs.github.com/en/github/administering-a-repository/about-protected-branches#require-status-checks-before-merging

@Chippers255, you have to do that part.

**Comment by Chippers255** [comment]
status checks enabled

**Comment by twentylemon** [comment]
So, the [compile script](https://github.com/Chippers255/duckbot/blob/main/scripts/build/compile.sh) doesn't actually catch all build errors. It runs some stuff and will catch things like import errors, but it won't catch symbol errors. For example, the following would pass the compile script:

`main.py`
```python
bot.add_cog(ErrorCog(bot))
```

`error_cog.py`
```python
class ErrorCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    def this_has_an_error(self):
        print(nothing)
```

`ErrorCog#this_has_an_error` actually needs to be executed for the error to show up. This _should_ happen in tests, but isn't guaranteed. A high code coverage requirement could help with that.

However, it is worth noting that the above will not kill duckbot. The bot would still be able to start up, whatever broken pieces should be the only things broken (so, `!error` would fail, but `!day` would still be fine).
