### ISSUE TITLE
Only send a single "don't thank robot" message

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#322]
See https://github.com/duck-dynasty/duckbot/blob/main/duckbot/cogs/robot/thanking_robot.py#L15

Currently, if the message content contains multiple "thanks," duckbot will response twice. Just needs a short circuit.

**Comment by jameshughes89** [comment]
How do we feel about `break` for quick fix?
https://github.com/duck-dynasty/duckbot/blob/main/duckbot/cogs/robot/thanking_robot.py#L16

**Comment by twentylemon** [comment]
I tend to prefer `return` over `break` where possible. But, that's the idea.
