### ISSUE TITLE
periodically change the activity/game duckbot is doing

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#329]
#219 added a random activity as opposed to a single hard coded activity (#108), discord says "DuckBot is playing the Banjo" or whatever. It'd be nice if we rotated through the list of available games every so often.

**Comment by jameshughes89** [comment]
Do you mean: 
(a) have more in the list?
(b) have a rotation of lists of games?
(c) change out the single list every so often?

**Comment by twentylemon** [comment]
(b) is what I meant. Not necessarily a determined rotation, something as simple as picking randomly from the existing list and updating the activity using a background task (though, either would be fine, so long as the activity changes without having to restart duckbot).
