### ISSUE TITLE
Add chance to also send a gif/image during day of the week announcement

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#35]
So like a 10% chance or whatever to be like:

> Yoo, it Monday brother.
> https://media.giphy.com/media/3o6fJbwYFe3SmVVQ4M/giphy.gif

Or however it gets embedded.

**Comment by Chippers255** [comment]
This GIF should be added to the Friday selection.

https://tenor.com/view/nicolas-cage-friday-feel-that-friday-feeling-feel-that-thats-friday-gif-12235300
