### ISSUE TITLE
Update Actions workflow to include rickrolls

### ISSUE THREAD

**Issue by Chippers255** [duck-dynasty/duckbot#350]
https://github.com/TejasvOnly/random-rickroll

**Comment by twentylemon** [comment]
That only seems to be for issues, so it'd have to be a new workflow for when issues are created.

How often would you want it to trigger? Like 5% chance or what?

**Comment by twentylemon** [comment]
The gif they use is also pretty low quality...

https://github.com/TejasvOnly/rickrolldemo/issues/24

**Comment by Chippers255** [comment]
So what you are saying is, we can build something better?

**Comment by twentylemon** [comment]
Yeah. I think we can fork it, change the gif and use our own action instead. Would allow us to use other images as well. 

Or build our own, if we want to avoid JavaScript.

**Comment by twentylemon** [comment]
https://github.com/duck-dynasty/rick-roll-action
