### ISSUE TITLE
chat users should be able to type YOLO to merge all active PRs without approval

### ISSUE THREAD

**Issue by Chippers255** [duck-dynasty/duckbot#39]

**Comment by twentylemon** [comment]
It should still require some approvals. We have a few checks on PRs, with code review only being one of them. If all the others pass, sure, yolo. I wouldn't want people to be able to break the build -- and thus bring down the bot -- through a chat command.

I'd also make it a little harder. A confirmation would be nice.

> Me: YOLO
> DuckBot: Bruh, that'll merge these god-awful pull requests: #x, #y... are you sure you trust them? I sure as hell don't.
> Me: YOLO DAMMIT
> DuckBut: F
> DuckBot: Merged. See you on the other side, brother.

**Comment by twentylemon** [comment]
We'd probably want duckbot to comment on the PRs saying _YOLO_.

**Comment by Chippers255** [comment]
#31 should probably be completed first

**Comment by twentylemon** [comment]
https://github.com/PyGithub/PyGithub
