### ISSUE TITLE
💮 Log Haikus  💮 

### ISSUE THREAD

**Issue by jameshughes89** [duck-dynasty/duckbot#508]
Based on _A Friendship in Haiku_, Duckbro should automatically log these. 

Simply saving them as .txt could work, but we defo do not want them in the repo.

**Comment by Chippers255** [comment]
We have a database that powers `weather`, but I am not sure how stateful it is on repo changes. We could have a dedicate haiku channel on Discord.

**Comment by twentylemon** [comment]
Discord has a search functionality. Search the server for "haiku detected" and you get all of them as is. I don't see any real benefit from introducing another way to do the same thing.

**Comment by jameshughes89** [comment]
> Search the server for "haiku detected" and you get all of them as is.

Sounds like this guy doesn't want to spend an hour automating something that takes 1min to do.

**Comment by twentylemon** [comment]
One minute? How slow do you type?

**Comment by EldaveO** [comment]
I think this would be a useful feature as it would allow for a mass dump of Haiku into a file. Which then would be easier to go through when publishing and writing the book. 

This does seems like more of limited use tool, meaning we would use it 1 - 5 times and then never again.

**Comment by twentylemon** [comment]
I'm just going to make an executive decision and say willnotfix. Use discord's search.

**Comment by Chippers255** [comment]
> I'm just going to make an executive decision and say willnotfix. Use discord's search.

+1
