### ISSUE TITLE
fix build status badge

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#646]
The badge in the readme that says the build status is busted. See https://github.com/badges/shields/issues/8671

**Comment by jameshughes89** [comment]
looks like it's a change of:

`https://img.shields.io/github/workflow/status/duck-dynasty/duckbot/DuckBot%20CI` 
to
`https://img.shields.io/github/actions/workflow/status/duck-dynasty/duckbot/python-package.yml?branch=main`

in README

But I don't want to break anything, so someone else do it.
