### ISSUE TITLE
try out `pytest-flake8-v2`

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#666]
`pytest-flake8` seems to be [dead](https://github.com/tholo/pytest-flake8/issues/91), with the owner not even showing up to say that people that want to take over the project can.

The issue above indirectly mentions this [fork](https://github.com/VRGhost/pytest-flake8) which is published as [pytest-flake8-v2](https://pypi.org/project/pytest-flake8-v2/). I imagine it's meant to be a drop in replacement but have not done any real research past finding the project.

**Comment by jameshughes89** [comment]
> I imagine it's meant to be a drop in replacement but have not done any real research past finding the project.

it'd be nice if the [repo](https://github.com/VRGhost/pytest-flake8) or [pipy](https://pypi.org/project/pytest-flake8-v2/) clearly mention this.

**Comment by jameshughes89** [comment]
[It also seems like the repo's aliveness is a bit of a standing issue](https://stackoverflow.com/questions/61743089/python-testing-with-flake8-and-pytest-results-in-attributeerror-application-o)
