### ISSUE TITLE
add a talk like Dave command

### ISSUE THREAD

**Issue by Chippers255** [duck-dynasty/duckbot#701]
Given the cost, ease of use, and context limits of the OpenAI API I am thinking we could create a new command to make duckbot talk or respond to people in the style of a person. I have chosen Dave in this example.

![image](https://user-images.githubusercontent.com/3149083/227315321-58d55235-33db-4c77-9486-25638c4539c7.png)
![image](https://user-images.githubusercontent.com/3149083/227315482-c45d434e-8fab-4302-a20f-30a96c6e63b3.png)
![image](https://user-images.githubusercontent.com/3149083/227315537-92859337-3a23-43d9-90ef-ce1221452a19.png)

**Comment by Chippers255** [comment]
Here is an example of it making a new message instead of responding to one.

![image](https://user-images.githubusercontent.com/3149083/227316371-a52d75f5-318f-4cc0-86b7-c90db79cadba.png)
![image](https://user-images.githubusercontent.com/3149083/227316508-f29b5688-4432-4e48-865c-2bd70275fdd8.png)

It seems to use better grammar and punctuation that the actual Dave but it keeps the same spirit.

**Comment by twentylemon** [comment]
This has lots of overlap with #119. I'm going to close this issue in favour of that one.
