### ISSUE TITLE
Duckbot should detect when a message is a haiku

### ISSUE THREAD

**Issue by Chippers255** [duck-dynasty/duckbot#79]
Duckbot should count syllables for messages. If the message has the correct amount syllables for a haiku it should return that message formatted as a haiku.

> Dave: It's a little weird. I think "kids these days" are more needy in general.
> DuckBot: It's a little weird.
>                I think "kids these days" are more
>                Needy in general.

**Comment by twentylemon** [comment]
http://www.gutenberg.org/ebooks/3204 is a possible place to start for syllable counting. The book is just a ton of words hyphenated, see [the giant list](http://www.gutenberg.org/files/3204/files/mhyph.txt). There seems to be a bunch of noise as well, non-Latin characters. Might be something better out there.

**Comment by twentylemon** [comment]
https://pypi.org/project/syllables/ also exists. But one of their examples shows them estimating the number of syllables in _estimate_ as 4. Not a great way to sell the library.

**Comment by twentylemon** [comment]
https://github.com/tlastowka/python-haikubot also exists. Just a big hardcoded list of words.
